In [18]:
data_list = [1,2,3]

In [19]:
data_list

[1, 2, 3]

In [2]:
import numpy as np

In [21]:
arr = np.array(data_list)

In [22]:
arr

array([1, 2, 3])

In [23]:
data_list2=[[1,2,3],[4,5,6],[7,8,9]]

In [24]:
arr2=np.array(data_list2)

In [25]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr3=np.array([1,2,3,4,5])

In [27]:
arr3

array([1, 2, 3, 4, 5])

In [28]:
arr3[0]

1

In [29]:
arr3[4]

5

In [30]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2[2][2]

9

In [32]:
arr2[0,1]

2

In [33]:
arr2[2,2]

9

In [34]:
arr2[3,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [35]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [43]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [85]:
np.eye(6)   ## birim matris

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [45]:
np.random.randint(0,10)   ## 0,10 arası random sayı. 0 dahil 10 dahil değil

1

In [46]:
np.random.randint(15)    ## 0,15 arası random sayı. 0 dahil 15 dahil değil

5

In [47]:
np.random.randint(1,10,5)    ## 1 ile 10 arası sayı üret listeye at

array([9, 1, 3, 7, 7])

In [48]:
np.random.rand(5)     ## 0 ile 1 arasında 5 sayı üret listeye at

array([0.83631067, 0.63342572, 0.76470676, 0.78980687, 0.95856761])

In [49]:
np.random.randn(5)    ##g 0 ile 1 arasında gaussian distribution ile 5 değer üretir listeye atar

array([ 0.47566095, -0.27047608, -1.0396774 ,  0.06301965, -0.68123277])

In [50]:
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arr.reshape(5,5)    ## arr'yi 5x5 lik bir matris yapar.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
newArray=np.random.randint(1,100,10)

In [54]:
newArray

array([94, 70,  3, 55, 72, 90, 65, 32, 83, 73])

In [55]:
newArray.max()

94

In [56]:
newArray.min()

3

In [57]:
newArray.sum()

637

In [58]:
newArray.mean()

63.7

In [59]:
newArray.argmax()

0

In [60]:
newArray.argmin()

2

In [13]:
detArray=np.random.randint(1,100,25)

In [14]:
detArray

array([26, 82, 62, 82, 67,  1, 15, 23, 77, 57, 63, 49, 95, 91, 27, 79, 14,
       99, 91,  3, 74, 60, 31, 77, 43])

In [15]:
detArray = detArray.reshape(5,5)

In [16]:
detArray

array([[26, 82, 62, 82, 67],
       [ 1, 15, 23, 77, 57],
       [63, 49, 95, 91, 27],
       [79, 14, 99, 91,  3],
       [74, 60, 31, 77, 43]])

In [17]:
np.linalg.det(detArray)    ## bu fonksiyon içerisine aldığı matrisin determinantını bulur

-46069938.00000028

In [18]:
detArray2=np.array([[1,2],[3,4]])

In [19]:
detArray2

array([[1, 2],
       [3, 4]])

In [20]:
np.linalg.det(detArray2)

-2.0000000000000004

In [21]:
round(np.linalg.det(detArray2))

-2.0

In [22]:
import numpy as np

In [23]:
arr=np.arange(1,10)

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[1]

2

In [26]:
arr[3]

4

In [27]:
arr[1:4]

array([2, 3, 4])

In [29]:
arr[:4]

array([1, 2, 3, 4])

In [30]:
arr[0:4]

array([1, 2, 3, 4])

In [31]:
arr[::2]

array([1, 3, 5, 7, 9])

In [32]:
arr[1::2]

array([2, 4, 6, 8])

In [33]:
arr[:3]

array([1, 2, 3])

In [34]:
arr[:3]=25

In [35]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [36]:
arr=np.arange(1,10)

In [37]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr2=arr

In [39]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr2[:3]=100

In [41]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [42]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [43]:
arr=np.arange(1,10)

In [44]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr2=arr.copy()

In [46]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr2[:3]=100

In [48]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [49]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
newArray=np.arange(20)

In [54]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
newArray.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
newArray=newArray.reshape(5,4)

In [58]:
newArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
newArray[0][0]

0

In [60]:
newArray[:,:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [61]:
newArray[:3,:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [62]:
newArray[:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
newArray[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
arr=np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [67]:
booleanArray=arr>3

In [68]:
booleanArray

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [70]:
arr[booleanArray]    ## arr filter

array([ 4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[arr>5]  ## arr filter

array([ 6,  7,  8,  9, 10])

In [73]:
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([1,2,3,4,5,6])

In [74]:
arr1+arr2

array([11, 22, 33, 44, 55, 66])

In [75]:
arr1-arr2

array([ 9, 18, 27, 36, 45, 54])

In [76]:
arr1*arr2

array([ 10,  40,  90, 160, 250, 360])

In [77]:
arr1

array([10, 20, 30, 40, 50, 60])

In [78]:
arr1+10

array([20, 30, 40, 50, 60, 70])

In [79]:
arr2

array([1, 2, 3, 4, 5, 6])

In [80]:
arr2-2

array([-1,  0,  1,  2,  3,  4])

In [81]:
arr1

array([10, 20, 30, 40, 50, 60])

In [82]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [83]:
arr1//3

array([ 3,  6, 10, 13, 16, 20], dtype=int32)

In [84]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])