##### Numpy'ı Dahil Edin

In [1]:
import numpy as np

##### 5 tane 1 barındıran bir array oluşturun

In [3]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [5]:
# Bu satırı çalıştırmayın

array([1., 1., 1., 1., 1.])

##### 5 tane 0 barındıran bir array oluşturun

In [4]:
y=np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [6]:
# Bu satırı çalıştırmayın

array([0., 0., 0., 0., 0.])

##### 2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [6]:
u=np.arange(2,100,2)
u

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
# Bu satırı çalıştırmayın

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

##### 5 tane 10 bulunan bir array oluşturun

In [15]:
on=np.ones(5)*10
on

array([10., 10., 10., 10., 10.])

In [10]:
# Bu satırı çalıştırmayın

array([10., 10., 10., 10., 10.])

##### 1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [17]:
x=np.arange(1,17)
x=x.reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
# Bu satırı çalıştırmayın

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### 4x4'lük bir birim matris oluşturun

In [21]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Bu satırı çalıştırmayın

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### 0 ile 5 arasında rastgele değerler üretin

In [44]:
np.random.rand()*5

4.762260456923802

In [20]:
# Bu satırı çalıştırmayın

4.5693236808831825

##### 5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [31]:
np.random.randn(5,5)

array([[ 1.27498291,  0.69253285,  0.07741419,  1.85518742, -0.23845318],
       [-1.42417966,  1.67088514,  1.06649142,  2.03681884, -0.43803816],
       [-0.90104768, -0.02269975,  0.37090702,  0.07675217,  0.39297719],
       [-0.48123876,  0.77803679,  1.43662738,  0.02246614,  0.60749068],
       [ 2.24985926, -0.08405056, -1.15259072, -2.05130595, -0.77712388]])

In [21]:
# Bu satırı çalıştırmayın

array([[-1.05647946,  0.88447651, -0.09589524,  0.707474  , -1.27075888],
       [ 1.98577112,  2.11969776, -0.62400642,  0.69932275,  0.11141592],
       [-0.71398274,  0.85916974,  0.51843923,  2.31872337,  0.48762873],
       [-1.18549889,  0.30847846,  1.0822357 ,  1.43461576, -0.10142078],
       [-0.15602908,  0.30583364,  1.69070191,  0.06727983, -0.17285088]])

##### 1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [34]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [23]:
# Bu satırı çalıştırmayın

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

### Array Indekslenmesi

In [36]:
arr  = np.arange(1,101).reshape(10,10)

In [37]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

##### Indeks işlemlerini kullanarak aşağıdaki sonuçları elde etmeye çalışın

In [38]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [85]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [39]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [31]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [41]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [34]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [43]:
arr[:3,1]

array([ 2, 12, 22])

In [36]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 2, 12, 22])

In [46]:
arr[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [37]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 2],
       [12],
       [22]])

In [47]:
arr[:,-1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [38]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### Array Operasyonları

Not: Arrayler rastgele sayılarla çalıştırıldığı için sizde çıkan sonuçlar buradakilerle aynı olmayacaktır.

In [48]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [49]:
arr1

array([[2, 3, 1],
       [3, 3, 0],
       [1, 4, 1]])

In [50]:
arr2

array([[2, 4, 1],
       [0, 2, 2],
       [3, 0, 2]])

##### İki Matrisi Toplayın

In [51]:
arr1+arr2

array([[4, 7, 2],
       [3, 5, 2],
       [4, 4, 3]])

##### İki Matrisi Çarpın

In [52]:
arr1*arr2

array([[ 4, 12,  1],
       [ 0,  6,  0],
       [ 3,  0,  2]])

##### arr1 matrisinin tüm elemanlarının ortalamasını bulun

In [53]:
arr1.mean()

2.0

##### arr1 matrisinin tüm elemanlarının toplamını bulun

In [54]:
arr1.sum()

18